######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 1 21:11:43 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common_defs.h inline_func.h matrix_op.h timer.h
SOURCES += linear_solvers.cpp main.cpp matrix_op.cpp timer.cpp
